directories:
  output: release
  buildResources: build
appId: com.company.frontend
productName: Meta
files:
  - filter:
      - dist/**/*
      - electron/**/*
win:
  target:
    - portable
    - nsis
  icon: public/icon.ico
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
electronVersion: 44.0.0
